customRecipes: true
silkSpawners: true
goldenArmor: true
sneakyArmor: true
bombArrows:  true
bombArrowRadius: 2.0
lightningArrows: true
multishotBow: true
dropPlayerHeads: true
piggybackRides: true
hideSpectators: true
speedyShulkers: true
globalEnderChest: false
conveyorBelts: true
conveyorSpeed: 0.25
elytraSprintBoost: 0.05
