version: 1.3.2
name: TheFarside
author: genandnic
description: Goonimati inspired gameplay tweaks!
main: com.genandnic.server.Main

commands:
  encase:
    description: Traps the specified player in bedrock
    usage: /encase <player>
    permission: Operator
  die:
    description: Kills the player
  suicide:
    description: Kills the player